"Name: \PR:PDTC_REPORT\FO:PDTC_SCREEN_OUTPUT\SE:BEGIN\EI
ENHANCEMENT 0 ZDOP_RAPOR_ENH_TAB.
*
*  LOOP AT SCREEN.
*    if screen-name = 'TABSTR_4'.
*     screen-active = 0.
*     MODIFY SCREEN.
*    ENDIF.
*  ENDLOOP.
ENDENHANCEMENT.
