"Name: \PR:ZDOP_ENHANCEMENT_SECTION_DEMO\IC:ZDOP_ENHANCEMENT_SECTION_DEMO\SE:END\EI
ENHANCEMENT 0 ZDOP_ENH_SECTION_DEMO_CODE.
*
  type-pools slis.
  data gs_layout type SLIS_LAYOUT_ALV.
  gs_layout-zebra = 'X'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
    I_STRUCTURE_NAME = 'EKKO'
    I_GRID_TITLE = 'ENHANCEMENT SECTION DEMO'
    IS_LAYOUT = gs_layout
  TABLES
    t_outtab = gt_ekko.
ENDENHANCEMENT.
