"Name: \TY:ZDOP_STRING_FUNCTIONS\ME:STRING_CONCATENATE\SE:END\EI
ENHANCEMENT 0 ZDOP_CLASS_ENHANCEMENT_SC.
  CONCATENATE ev_sonuc iv_string3
              INTO ev_sonuc SEPARATED BY space.

ENDENHANCEMENT.
