"Name: \PR:ZDOP_FORM_EXIT\FO:EKKO_KAYITLARI_SEC\SE:END\EI
ENHANCEMENT 0 ZDOP_FORM_EXIT.
*İLK 100 KAYITTAN SONRAKİLERİ SİL VE BELGE NUMARASINA GÖRE SIRALA
  DELETE GT_EKKO FROM 101.
  SORT GT_EKKO BY EBELN DESCENDING.
ENDENHANCEMENT.
