*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZDOP_MV_EMPLOYEE................................*
FORM GET_DATA_ZDOP_MV_EMPLOYEE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZDOP_EMPLOYEE WHERE
(VIM_WHERETAB) .
    CLEAR ZDOP_MV_EMPLOYEE .
ZDOP_MV_EMPLOYEE-MANDT =
ZDOP_EMPLOYEE-MANDT .
ZDOP_MV_EMPLOYEE-EMPID =
ZDOP_EMPLOYEE-EMPID .
ZDOP_MV_EMPLOYEE-EMPNAME =
ZDOP_EMPLOYEE-EMPNAME .
ZDOP_MV_EMPLOYEE-BIRTHDATE =
ZDOP_EMPLOYEE-BIRTHDATE .
ZDOP_MV_EMPLOYEE-ADDRESS =
ZDOP_EMPLOYEE-ADDRESS .
<VIM_TOTAL_STRUC> = ZDOP_MV_EMPLOYEE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZDOP_MV_EMPLOYEE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZDOP_MV_EMPLOYEE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZDOP_MV_EMPLOYEE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZDOP_EMPLOYEE WHERE
  EMPID = ZDOP_MV_EMPLOYEE-EMPID AND
  EMPNAME = ZDOP_MV_EMPLOYEE-EMPNAME AND
  BIRTHDATE = ZDOP_MV_EMPLOYEE-BIRTHDATE .
    IF SY-SUBRC = 0.
    DELETE ZDOP_EMPLOYEE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZDOP_EMPLOYEE WHERE
  EMPID = ZDOP_MV_EMPLOYEE-EMPID AND
  EMPNAME = ZDOP_MV_EMPLOYEE-EMPNAME AND
  BIRTHDATE = ZDOP_MV_EMPLOYEE-BIRTHDATE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZDOP_EMPLOYEE.
    ENDIF.
ZDOP_EMPLOYEE-MANDT =
ZDOP_MV_EMPLOYEE-MANDT .
ZDOP_EMPLOYEE-EMPID =
ZDOP_MV_EMPLOYEE-EMPID .
ZDOP_EMPLOYEE-EMPNAME =
ZDOP_MV_EMPLOYEE-EMPNAME .
ZDOP_EMPLOYEE-BIRTHDATE =
ZDOP_MV_EMPLOYEE-BIRTHDATE .
ZDOP_EMPLOYEE-ADDRESS =
ZDOP_MV_EMPLOYEE-ADDRESS .
    IF SY-SUBRC = 0.
    UPDATE ZDOP_EMPLOYEE .
    ELSE.
    INSERT ZDOP_EMPLOYEE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZDOP_MV_EMPLOYEE-UPD_FLAG,
STATUS_ZDOP_MV_EMPLOYEE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZDOP_MV_EMPLOYEE.
  SELECT SINGLE * FROM ZDOP_EMPLOYEE WHERE
EMPID = ZDOP_MV_EMPLOYEE-EMPID AND
EMPNAME = ZDOP_MV_EMPLOYEE-EMPNAME AND
BIRTHDATE = ZDOP_MV_EMPLOYEE-BIRTHDATE .
ZDOP_MV_EMPLOYEE-MANDT =
ZDOP_EMPLOYEE-MANDT .
ZDOP_MV_EMPLOYEE-EMPID =
ZDOP_EMPLOYEE-EMPID .
ZDOP_MV_EMPLOYEE-EMPNAME =
ZDOP_EMPLOYEE-EMPNAME .
ZDOP_MV_EMPLOYEE-BIRTHDATE =
ZDOP_EMPLOYEE-BIRTHDATE .
ZDOP_MV_EMPLOYEE-ADDRESS =
ZDOP_EMPLOYEE-ADDRESS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZDOP_MV_EMPLOYEE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZDOP_MV_EMPLOYEE-EMPID TO
ZDOP_EMPLOYEE-EMPID .
MOVE ZDOP_MV_EMPLOYEE-EMPNAME TO
ZDOP_EMPLOYEE-EMPNAME .
MOVE ZDOP_MV_EMPLOYEE-BIRTHDATE TO
ZDOP_EMPLOYEE-BIRTHDATE .
MOVE ZDOP_MV_EMPLOYEE-MANDT TO
ZDOP_EMPLOYEE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZDOP_EMPLOYEE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZDOP_EMPLOYEE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZDOP_EMPLOYEE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
